cmd_/home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.o := gcc -Wp,-MD,/home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/.div64.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.6/include -I/home/dank/src/linux-3.1.y/arch/x86/include -Iarch/x86/include/generated -Iinclude  -include /home/dank/src/linux-3.1.y/include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -m64 -march=core2 -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DLINUX -D_LINUX_ -D__KERNEL__=1 -DSUPPORT_ARRAY -DDBG=0 -DBITS_PER_LONG=64 -DMODVERSIONS -DMODULE -Idrivers/scsi -I/home/dank/rr2640-linux-src-v1.3-legacy_single/inc/linux -I/home/dank/rr2640-linux-src-v1.3-legacy_single/inc -I/home/dank/rr2640-linux-src-v1.3-legacy_single/osm/linux  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(div64)"  -D"KBUILD_MODNAME=KBUILD_STR(rr26xx)" -c -o /home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.o /home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.c

source_/home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.o := /home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.c

deps_/home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.o := \

/home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.o: $(deps_/home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.o)

$(deps_/home/dank/rr2640-linux-src-v1.3-legacy_single/product/rr2640/linuxls/.build/div64.o):
